AWSTemplateFormatVersion: 2010-09-09
Description: This template provisions our dev network environment
Metadata: {}

Parameters: 
  # Dev VPC Parameters
  DevVPCCidirBlockPara:
    Description: please provide your DevVPC Cidr Block
    Type: AWS::SSM::Parameter::Value<String>
  
  DevVPCEnableDnsSupportPara:
    Description: please EnableDnsSupport (True/False)
    Type: String

  # Webserver subnet parameters
  DevWebserverSubnetAZPara:
    Description: please select an AZ for the DevWebserver Subnet
    Type: AWS::EC2::AvailabilityZone::Name
    
  DevWebserverSubnetCidrBlockPara:
    Description: please provide your DevWebserverSubnet Cidr Block
    Type: AWS::SSM::Parameter::Value<String>
    
  # Webserver subnet parameters
  DevAppserverSubnetAZPara:
    Description: please select an AZ for the DevAppserver Subnet
    Type: AWS::EC2::AvailabilityZone::Name
    
  DevAppserverSubnetCidrBlockPara:
    Description: please provide your DevAppserverSubnet Cidr Block
    Type: AWS::SSM::Parameter::Value<String>

  # DBserver subnet parameters
  DevDBserverSubnetAZPara:
    Description: please select an AZ for the DevDBserver Subnet
    Type: AWS::EC2::AvailabilityZone::Name
    
  DevDBserverSubnetCidrBlockPara:
    Description: please provide your DevDBserverSubnet Cidr Block
    Type: AWS::SSM::Parameter::Value<String>

Mappings: {}

Conditions: {}

Resources:
  # development vpc
  DevVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref DevVPCCidirBlockPara
      EnableDnsSupport: !Ref DevVPCEnableDnsSupportPara
      Tags:
        - Key: Name
          Value: DevVPC
  # webserver subnet 
  DevWebserverSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref DevWebserverSubnetAZPara
      VpcId: !Ref DevVPC
      CidrBlock: !Ref DevWebserverSubnetCidrBlockPara
      Tags:
        - Key: Name
          Value: DevWebserverSubnet

  # appserver subnets
  DevAppserverSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref DevAppserverSubnetAZPara
      VpcId: !Ref DevVPC
      CidrBlock: !Ref DevAppserverSubnetCidrBlockPara
      Tags:
        - Key: Name
          Value: DevAppserverSubnet

  # database subnet
  DevDBserverSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref DevDBserverSubnetAZPara
      VpcId: !Ref DevVPC
      CidrBlock: !Ref DevDBserverSubnetCidrBlockPara
      Tags:
        - Key: Name
          Value: DevDBserverSubnet

Outputs: {}