AWSTemplateFormatVersion: 2010-09-09
Description: "EC2 instance automation for our development Env"
Metadata: {}

Parameters: {}

Mappings: {}

Conditions: {}

Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: 
      DisableApiTermination: 
      ImageId: 
      InstanceType: 
      Monitoring: true|false
      SecurityGroupIds:
        - sg-id
      UserData: !Base64
        #!/bin/bash -ex
        # put your script here
      Tags:
        - Key: key
          Value: value

Outputs: {}